import express from 'express';
import { createStartupProfile, getMyStartupProfile, updateStartupProfile,matchInvestors, getStartupProfileById } from "../controllers/startupController.js";
import authMiddleware from "../middleware/authMiddleware.js";
const router=express.Router();
router.post("/create",authMiddleware,createStartupProfile);
router.get("/me", authMiddleware, getMyStartupProfile);
router.put("/update",authMiddleware,updateStartupProfile);
router.get("/match-investors",authMiddleware,matchInvestors);
router.get("/profile/:userId", authMiddleware, getStartupProfileById);
export default router;